### PR TITLE
Remove the package variable minClassSize

### PR DESCRIPTION
**Pull request by allisonmorgan**
Closes https://github.com/lytics/multibayes/issues/16 😷 

cc @drewlanenga

### CODE REVIEW

**Comment by drewlanenga** [comment]
hmm... this brings up a good point.  i'm not sure i like [`minClassSize`](https://github.com/lytics/multibayes/blob/11b8faea1cd35d54279889e28bc89993e5baa2cb/bayes.go#L9) being a package variable.  what if we passed it through the constructor and made it a property on the actual classifier?

**Comment by allisonmorgan** [comment]
@drewlanenga Yeah that approach also makes sense to me. I've updated this PR to reflect those changes.

**Comment by drewlanenga** [comment]
Thanks! :+1:

**Comment by allisonmorgan** [comment]
@drewlanenga Can you merge? I no longer have permission to

**Pull request merged**
